name: salon_app
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  cupertino_icons: ^1.0.2
  carousel_slider: ^5.1.1

  google_maps_flutter: ^2.6.1
  flutter_polyline_points: ^2.0.0

  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  cloud_firestore: ^4.17.3
  firebase_storage: ^11.7.7

  google_sign_in: ^6.2.1

  date_picker_timeline: ^1.2.6
  provider: ^6.1.2

  # ✅ chọn ảnh từ điện thoại/laptop (Android/Windows)
  file_picker: ^8.0.0
  firebase_messaging: ^14.9.4

  # ✅ mở link thanh toán
  url_launcher: ^6.3.2

  # ✅ gọi backend tạo link thanh toán VNPAY
  http: ^1.2.2

dependency_overrides:
  flutter_plugin_android_lifecycle: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
